import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Breadcrumb, BookStrip, Related, Shell } from "@/components/SiteShell";
import CopyAddress from "@/components/CopyAddress";
import PhotoGallery from "@/components/PhotoGallery";
import { descriptions, href, labels, photo, site, type Locale, type PageKey } from "@/lib/site";

const say = (locale: Locale, ko: string, en: string) => locale === "ko" ? ko : en;
const external = { target: "_blank", rel: "noopener noreferrer" } as const;

export function makeMetadata(locale: Locale, page: PageKey): Metadata {
  const origin = process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "");
  const title = page === "home" ? say(locale, "강산재 | 홍천 한옥 숙소", "Kangsanjae | Hanok Stay in Hongcheon") : `${labels[page][locale]} | ${site.englishName}`;
  const description = descriptions[page][locale];
  return { title, description, openGraph: { title, description, type: "website", locale: locale === "ko" ? "ko_KR" : "en_US", ...(origin ? { url: `${origin}${href(locale, page)}`, images: [{ url: `${origin}${photo("hero-hanok")}`, width: 1280, height: 853, alt: "Kangsanjae hanok" }] } : {}) }, ...(origin ? { alternates: { canonical: `${origin}${href(locale, page)}`, languages: { ko: `${origin}${href("ko", page)}`, en: `${origin}${href("en", page)}` } } } : {}) };
}

function Picture({ file, alt, className = "", priority = false, sizes = "(max-width: 700px) 100vw, 50vw" }: { file: string; alt: string; className?: string; priority?: boolean; sizes?: string }) {
  return <div className={`picture ${className}`}><Image src={photo(file)} alt={alt} fill sizes={sizes} priority={priority} /></div>;
}
function Eyebrow({ children }: { children: React.ReactNode }) { return <span className="eyebrow">{children}</span>; }
function ArrowLink({ locale, page, children }: { locale: Locale; page: PageKey; children?: React.ReactNode }) { return <Link className="text-link" href={href(locale, page)}>{children ?? labels[page][locale]} <span aria-hidden="true">→</span></Link>; }
function PageIntro({ locale, title, description, image, eyebrow }: { locale: Locale; title: string; description: string; image: string; eyebrow: string }) {
  return <><div className="sub-hero"><Picture file={image} alt={title} priority sizes="100vw" /><div className="sub-hero-shade" /><div className="wrap sub-hero-content"><Eyebrow>{eyebrow}</Eyebrow><h1>{title}</h1><p>{description}</p></div></div><Breadcrumb locale={locale} current={Object.entries(labels).find(([, v]) => v[locale] === title)?.[0] as PageKey || "home"} /></>;
}
function HeaderBlock({ eyebrow, title, description }: { eyebrow: string; title: string; description?: string }) { return <div className="section-heading"><Eyebrow>{eyebrow}</Eyebrow><h2>{title}</h2>{description && <p>{description}</p>}</div>; }
function PhotoGrid({ items, locale, columns = 3 }: { items: { file: string; ko: string; en: string }[]; locale: Locale; columns?: number }) { return <div className={`photo-cards columns-${columns}`}>{items.map(item => <figure key={item.file}><Picture file={item.file} alt={item[locale]} /><figcaption>{item[locale]}</figcaption></figure>)}</div>; }

function HomePage({ locale }: { locale: Locale }) {
  return <>
    <section className="home-hero"><Picture file="hero-hanok" alt={say(locale, "마당과 한옥 전경", "Hanok and courtyard at Kangsanjae")} className="home-hero-photo" priority sizes="100vw" /><div className="home-hero-shade" /><div className="wrap home-hero-content"><Eyebrow>HANOK STAY · HONGCHEON</Eyebrow><h1>{locale === "ko" ? <>한옥에 머물고,<br />자연의 속도로 쉬다.</> : <>Stay in a Hanok.<br />Slow Down in Nature.</>}</h1><p>{say(locale, "강원도 홍천, 강산재에서 보내는 고요한 하루.", "A peaceful retreat at Kangsanjae, Hongcheon, South Korea.")}</p><div className="hero-actions"><Link className="button button-light" href={href(locale, "reservation")}>{say(locale, "예약하기", "Book Your Stay")} <span aria-hidden="true">→</span></Link><ArrowLink locale={locale} page="stay">{say(locale, "객실 둘러보기", "Explore the Stay")}</ArrowLink></div><span className="hero-note">{say(locale, "전통 한옥 · 자연 속 휴식", "Traditional Hanok · A Retreat in Nature")}</span></div></section>
    <section className="intro-section border-section"><div className="wrap intro-grid"><div><Eyebrow>ABOUT KANGSANJAE</Eyebrow><h2>{locale === "ko" ? <>머무는 순간이<br />여행이 되는 곳</> : <>A place to stay.<br />A moment to remember.</>}</h2></div><div className="intro-copy"><p>{locale === "ko" ? <>나무의 온기와 마당의 바람,<br />처마 아래 흐르는 느긋한 시간.<br />강산재에서 온전한 쉼을 만나보세요.</> : <>The warmth of wood. The breeze in the courtyard.<br />Time slows beneath the eaves.<br />Find your quiet moment at Kangsanjae.</>}</p><ArrowLink locale={locale} page="about" /></div></div></section>
    <section className="section border-section"><div className="wrap"><HeaderBlock eyebrow="STAY" title={say(locale, "함께 머무는 한옥", "A Hanok to Share")} /><div className="stay-feature"><div className="stay-feature-photos"><Picture file="living-room" alt={say(locale, "강산재 본채의 실내", "Main House interior")} /><Picture file="floor-bedding" alt={say(locale, "바닥 침구 공간", "Floor bedding room")} className="stay-feature-small" /></div><div className="stay-feature-copy"><h3>{say(locale, "본채", "Main House")}</h3><span className="muted">Main House</span><p>{say(locale, "한옥의 온기를 함께 나누는 공간", "Share the warmth of a traditional Korean home.")}</p><div className="feature-list"><span>{say(locale, "실내 공간", "Living spaces")}</span><span>{say(locale, "침구 안내", "Sleeping areas")}</span><span>{say(locale, "편의시설", "Amenities")}</span></div><Link className="button button-dark" href={href(locale, "mainHouse")}>{say(locale, "본채 자세히 보기", "Explore the Main House")} →</Link></div></div></div></section>
    <section className="section border-section"><div className="wrap"><HeaderBlock eyebrow="EXPERIENCES" title={say(locale, "강산재에서의 하루", "A Day at Kangsanjae")} /><PhotoGrid locale={locale} items={[{ file: "courtyard", ko: "마당에서 쉬는 오후", en: "Afternoons in the courtyard" }, { file: "living-room", ko: "한옥에 머무는 시간", en: "Quiet moments indoors" }, { file: "firepit", ko: "불멍으로 깊어지는 밤", en: "Evenings by the fire" }]} /><div className="section-end"><ArrowLink locale={locale} page="experiences">{say(locale, "즐길 거리 살펴보기", "Explore Experiences")}</ArrowLink></div></div></section>
    <section className="filming-banner"><Picture file="hanok-side" alt={say(locale, "드라마 촬영지로 소개된 강산재 한옥", "Kangsanjae hanok exterior")} sizes="100vw" /><div className="filming-overlay" /><div className="wrap filming-content"><Eyebrow>FILMING LOCATION</Eyebrow><h2>{say(locale, "드라마 속 그 한옥, 강산재", "The Hanok from XO, Kitty")}</h2><p>{say(locale, "〈XO, Kitty〉 시즌 2 촬영지", "A filming location for XO, Kitty Season 2")}</p><ArrowLink locale={locale} page="filming">{say(locale, "촬영지 이야기", "Discover the Story")}</ArrowLink></div></section>
    <section className="section border-section"><div className="wrap"><HeaderBlock eyebrow="SEASONS" title={say(locale, "계절마다 새로운 풍경", "A Different Beauty in Every Season")} /><PhotoGrid locale={locale} items={[{ file: "green-lawn", ko: "초록빛 마당", en: "A courtyard in green" }, { file: "snow-jars", ko: "눈 내린 한옥", en: "A hanok in the snow" }, { file: "evening-hanok", ko: "따뜻한 밤", en: "Warm nights" }]} /><div className="section-end"><ArrowLink locale={locale} page="gallery">{say(locale, "갤러리 전체 보기", "View the Gallery")}</ArrowLink></div></div></section>
    <BookStrip locale={locale} />
  </>;
}

function AboutPage({ locale }: { locale: Locale }) { return <><PageIntro locale={locale} eyebrow="ABOUT KANGSANJAE" title={labels.about[locale]} description={say(locale, "한옥과 자연 사이, 느린 하루가 시작되는 곳.", "A quiet day begins where hanok meets nature.")} image="garden-house" /><section className="section"><div className="wrap split-section"><div><HeaderBlock eyebrow="A PLACE TO PAUSE" title={say(locale, "자연의 리듬을 따라 머무르다", "Settle into Nature's Rhythm")} /><p>{say(locale, "강산재는 홍천의 산과 숲을 가까이 두고 있는 한옥 숙소입니다. 마당을 걷고, 처마 아래 앉아 계절의 변화를 느껴보세요.", "Kangsanjae is a traditional Korean house surrounded by the mountains and forest of Hongcheon. Walk through the courtyard and watch the seasons change beneath its eaves.")}</p><p>{say(locale, "나무 기둥과 기와지붕, 창으로 들어오는 빛이 공간의 분위기를 만듭니다. 숙소의 실제 모습을 사진으로 먼저 만나보세요.", "Timber pillars, tiled roofs and light through the windows shape the stay. Explore the real spaces in the photographs below.")}</p><ArrowLink locale={locale} page="stay" /></div><Picture file="hanok-eaves" alt={say(locale, "강산재 한옥 처마", "Hanok eaves")} /></div></section><section className="section soft-section"><div className="wrap"><HeaderBlock eyebrow="THE HANOK" title={say(locale, "한옥 안팎의 풍경", "Inside and Around the Hanok")} /><PhotoGrid locale={locale} items={[{file:"roof-detail",ko:"기와지붕의 곡선",en:"Curved tiled roof"},{file:"living-room",ko:"나무의 온기가 느껴지는 실내",en:"Warm timber interior"},{file:"garden-gate",ko:"마당의 작은 문",en:"Gate in the garden"}]} /></div></section><Related locale={locale} items={["mainHouse","experiences","reservation"]} /><BookStrip locale={locale} /></>;
}

function FilmingPage({ locale }: { locale: Locale }) { return <><PageIntro locale={locale} eyebrow="FILMING LOCATION" title={labels.filming[locale]} description={say(locale, "〈XO, Kitty〉 시즌 2의 촬영지로 소개된 한옥.", "A hanok listed as a filming location for XO, Kitty Season 2.")} image="hanok-side" /><section className="section"><div className="wrap split-section"><div><HeaderBlock eyebrow="XO, KITTY SEASON 2" title={say(locale, "화면 밖에서도 이어지는 한옥의 풍경", "The Hanok Beyond the Screen")} /><p>{say(locale, "강산재의 본채 예약 상품에는 이곳이 〈XO, Kitty〉 시즌 2 촬영장소로 소개되어 있습니다. 이 페이지에서는 강산재의 실제 한옥과 마당을 보여드립니다.", "The host's Main House listing describes Kangsanjae as a filming location for XO, Kitty Season 2. Here you can see the real hanok and courtyard.")}</p><p>{say(locale, "촬영 장면별 정확한 공간은 확인되지 않았습니다. 이 공간은 현재 숙박 예약을 통해 경험할 수 있습니다.", "Specific scenes have not been matched to individual spaces. The property can be experienced through a stay.")}</p><a className="text-link" href={site.airbnb} {...external}>{say(locale, "호스트의 숙소 소개 확인", "Read the host listing")} ↗</a></div><Picture file="main-exterior" alt={say(locale, "강산재 한옥 본채", "Main House exterior")} /></div></section><section className="section soft-section"><div className="wrap"><HeaderBlock eyebrow="REAL SPACES" title={say(locale, "강산재의 실제 공간", "The Real Kangsanjae")} /><PhotoGrid locale={locale} items={[{file:"courtyard",ko:"한옥과 마당",en:"Hanok and courtyard"},{file:"wood-detail",ko:"나무 기둥과 창",en:"Timber and windows"},{file:"evening-hanok",ko:"저녁의 한옥",en:"Hanok at dusk"}]} /></div></section><Related locale={locale} items={["gallery","stay","reservation"]} /><BookStrip locale={locale} /></>;
}

function StayPage({ locale }: { locale: Locale }) { return <><PageIntro locale={locale} eyebrow="STAY" title={labels.stay[locale]} description={say(locale, "확인된 강산재 본채에서 한옥의 시간을 보내세요.", "Stay in the verified Main House at Kangsanjae.")} image="main-exterior" /><section className="section"><div className="wrap"><HeaderBlock eyebrow="MAIN HOUSE" title={say(locale, "본채", "Main House")} description={say(locale, "한옥 안의 실내 공간과 마당을 함께 만나는 숙소입니다.", "A hanok stay with indoor living spaces and a courtyard.")} /><div className="listing-card"><Picture file="living-room" alt={say(locale, "본채 실내", "Main House interior")} /><div><Eyebrow>HANOK STAY</Eyebrow><h3>{say(locale, "강산재 본채", "Kangsanjae Main House")}</h3><p>{say(locale, "한옥의 나무결이 느껴지는 실내와 침구 공간, 주방과 욕실을 사진으로 살펴보세요. 최신 인원·요금·이용 조건은 예약 상품에서 확인할 수 있습니다.", "Explore the timber interiors, sleeping spaces, kitchen and bathroom. Check the listing for current guest limits, prices and house rules.")}</p><div className="listing-actions"><Link className="button button-dark" href={href(locale, "mainHouse")}>{say(locale, "본채 자세히 보기", "Explore the Main House")} →</Link><a className="text-link" href={site.airbnb} {...external}>{say(locale, "Airbnb에서 예약", "Book on Airbnb")} ↗</a></div></div></div></div></section><Related locale={locale} items={["mainHouse","guide","reservation"]} /><BookStrip locale={locale} /></>;
}

function MainHousePage({ locale }: { locale: Locale }) { return <><PageIntro locale={locale} eyebrow="MAIN HOUSE" title={labels.mainHouse[locale]} description={say(locale, "전통 한옥의 온기와 현대적인 생활 공간을 함께.", "Traditional hanok character with spaces for a comfortable stay.")} image="hero-hanok" /><section className="section"><div className="wrap"><HeaderBlock eyebrow="A CLOSER LOOK" title={say(locale, "한옥 안의 하루", "A Day Inside the Hanok")} /><p className="lead-narrow">{say(locale, "강산재 본채 예약 상품에서 확인되는 공간을 중심으로 소개합니다. 사진 속 방과 실제 배정·이용 범위는 예약 전 상품 설명과 호스트 안내를 확인해 주세요.", "This page introduces spaces shown in the Main House listing. Confirm the exact rooms and areas included with the host before booking.")}</p><div className="detail-grid"><Picture file="living-room" alt={say(locale,"나무가 드러난 넓은 실내","Open timber interior")} /><Picture file="dining-kitchen" alt={say(locale,"식탁과 주방","Dining space and kitchen")} /><Picture file="floor-bedding" alt={say(locale,"바닥 침구 공간","Floor bedding space")} /><Picture file="bedroom" alt={say(locale,"침대가 있는 방","Room with bed")} /></div></div></section><section className="section soft-section"><div className="wrap"><HeaderBlock eyebrow="SPACES & AMENITIES" title={say(locale, "공간과 편의시설", "Spaces and Amenities")} /><div className="info-cards"><article><h3>{say(locale,"실내와 침구","Living and sleeping")}</h3><p>{say(locale,"본채 상품에는 침대와 바닥에 펴는 침구 공간이 안내되어 있습니다. 온돌은 바닥을 따뜻하게 데우는 한국식 난방 방식입니다.","The listing shows beds and floor bedding. Ondol is a traditional Korean system that warms the floor beneath the sleeping area.")}</p></article><article><h3>{say(locale,"주방과 욕실","Kitchen and bathrooms")}</h3><p>{say(locale,"주방과 욕실이 마련되어 있습니다. 최신 시설 목록과 이용 범위는 Airbnb 상품 설명에서 확인해 주세요.","A kitchen and bathrooms are listed. Check Airbnb for the current amenity list and access details.")}</p></article><article><h3>{say(locale,"마당과 야외 공간","Courtyard and outdoors")}</h3><p>{say(locale,"마당과 정원 풍경이 한옥을 둘러싸고 있습니다. 화덕·바비큐 등의 이용 조건은 호스트에게 먼저 확인해 주세요.","The hanok opens onto a courtyard and garden. Please confirm any firepit or barbecue arrangements with the host first.")}</p></article></div></div></section><section className="section"><div className="wrap"><HeaderBlock eyebrow="IN THE DETAILS" title={say(locale,"사진으로 살펴보기","See the Details")} /><PhotoGrid locale={locale} items={[{file:"bathroom",ko:"욕실",en:"Bathroom"},{file:"loft-bedroom",ko:"다락의 침구 공간",en:"Loft sleeping space"},{file:"interior-detail",ko:"실내 나무 디테일",en:"Interior timber details"}]} /><div className="section-end"><a className="button button-dark" href={site.airbnb} {...external}>{say(locale,"본채 예약 상품 확인","View Main House on Airbnb")} ↗</a></div></div></section><Related locale={locale} items={["guide","gallery","reservation"]} /><BookStrip locale={locale} /></>;
}

function ExperiencesPage({ locale }: { locale: Locale }) { return <><PageIntro locale={locale} eyebrow="EXPERIENCES" title={labels.experiences[locale]} description={say(locale,"한옥과 마당, 숲에서 보내는 각자의 시간.","Make room for your own pace in the hanok, courtyard and forest.")} image="pavilion-view" /><section className="section"><div className="wrap"><HeaderBlock eyebrow="SLOW MOMENTS" title={say(locale,"강산재에서의 하루","A Day at Kangsanjae")} /><div className="experience-rows">{[{file:"green-lawn",ko:"마당에서 쉬는 오후",en:"An afternoon in the courtyard",bodyKo:"햇살을 받는 잔디마당과 한옥의 처마가 하루의 풍경을 만듭니다.",bodyEn:"Sunlight in the courtyard and the hanok eaves set the pace of the afternoon."},{file:"forest-path",ko:"숲길을 걷는 시간",en:"A walk through the trees",bodyKo:"강산재의 숲길 사진을 따라 자연을 가까이 만나보세요. 현장 이용 범위는 호스트 안내를 확인해 주세요.",bodyEn:"Follow the photographed forest path and spend time close to nature. Ask the host which areas are available during your stay."},{file:"firepit",ko:"불빛이 머무는 밤",en:"An evening by the fire",bodyKo:"마당의 불빛이 밤 풍경을 바꿉니다. 불멍·바비큐는 날짜와 현장 상황에 따른 제공 조건을 예약 전 확인해 주세요.",bodyEn:"Firelight changes the evening courtyard. Confirm firepit and barbecue availability and conditions before booking."}].map(item => <article className="experience-row" key={item.file}><Picture file={item.file} alt={item[locale]} /><div><Eyebrow>AT KANGSANJAE</Eyebrow><h3>{item[locale]}</h3><p>{locale === "ko" ? item.bodyKo : item.bodyEn}</p></div></article>)}</div></div></section><Related locale={locale} items={["gallery","guide","reservation"]} /><BookStrip locale={locale} /></>;
}

function GalleryPage({ locale }: { locale: Locale }) { return <><PageIntro locale={locale} eyebrow="GALLERY" title={labels.gallery[locale]} description={say(locale,"한옥의 안과 밖, 계절과 시간에 따라 달라지는 풍경.","Inside and outside the hanok, through changing seasons and light.")} image="misty-mountain" /><section className="section"><div className="wrap"><HeaderBlock eyebrow="MOMENTS IN PHOTOS" title={say(locale,"사진으로 만나는 강산재","Kangsanjae in Pictures")} /><PhotoGallery locale={locale} /></div></section><Related locale={locale} items={["about","stay","reservation"]} /><BookStrip locale={locale} /></>;
}

const faq = [
  { koQ: "입·퇴실 시간은 언제인가요?", enQ: "When are check-in and check-out?", koA: "예약 날짜와 상품에 표시되는 최신 입·퇴실 시간을 Airbnb에서 확인해 주세요.", enA: "Please check the current check-in and check-out times on the Airbnb listing for your dates." },
  { koQ: "몇 명까지 머물 수 있나요?", enQ: "How many guests can stay?", koA: "본채 상품에 표시된 최대 인원과 인원별 예약 조건을 확인해 주세요. 인원 변경은 예약처 또는 호스트와 상의해 주세요.", enA: "Check the Main House listing for its current guest limit and booking conditions. Discuss changes with the host through Airbnb." },
  { koQ: "침대와 온돌 침구가 있나요?", enQ: "Are there beds and floor bedding?", koA: "공개 본채 상품에는 침대와 바닥 침구 공간이 소개되어 있습니다. 실제 배정과 침구 수량은 예약 전에 확인해 주세요.", enA: "The public Main House listing shows beds and Korean floor bedding. Confirm the exact sleeping arrangement before booking." },
  { koQ: "식사나 취사가 가능한가요?", enQ: "Can we cook or have meals provided?", koA: "주방은 공개 상품의 편의시설에 표시되어 있습니다. 식사 제공 여부와 취사 세부 규정은 호스트에게 확인해 주세요.", enA: "A kitchen appears among the listed amenities. Ask the host about cooking rules and whether any meals are offered." },
  { koQ: "주차할 수 있나요?", enQ: "Is parking available?", koA: "본채 Airbnb 상품에 건물 부지 내 무료 주차가 표시되어 있습니다. 차량 대수와 주차 위치는 예약 전 확인해 주세요.", enA: "The Main House Airbnb listing shows free parking on the property. Confirm vehicle limits and the exact parking area before arrival." },
  { koQ: "어린이나 반려동물도 함께할 수 있나요?", enQ: "Are children or pets allowed?", koA: "동반 가능 여부와 추가 조건은 예약 날짜의 상품 규정을 확인하고 호스트에게 문의해 주세요.", enA: "Check the listing's current rules for children and pets, and message the host if needed." },
  { koQ: "취소 및 환불 조건은 어떻게 되나요?", enQ: "What is the cancellation policy?", koA: "예약 화면에 적용되는 취소·환불 정책을 결제 전에 확인해 주세요.", enA: "Review the cancellation policy shown during booking before confirming payment." },
  { koQ: "해외 여행자도 예약할 수 있나요?", enQ: "Can international guests book?", koA: "Airbnb 상품을 통해 예약 가능 여부를 확인할 수 있습니다. 언어 지원이나 도착 안내는 플랫폼 메시지로 호스트에게 문의해 주세요.", enA: "Check availability through Airbnb. You can message the host there about language support and arrival instructions." },
];
function GuidePage({ locale }: { locale: Locale }) { return <><PageIntro locale={locale} eyebrow="STAY GUIDE" title={labels.guide[locale]} description={say(locale,"예약 전 확인하면 좋은 정보를 모았습니다.","The practical details to review before your stay.")} image="interior-detail" /><section className="section"><div className="wrap"><HeaderBlock eyebrow="BEFORE YOU ARRIVE" title={say(locale,"이용 안내·FAQ","Stay Guide & FAQ")} /><div className="faq-list">{faq.map(item => <details key={item.koQ}><summary>{locale === "ko" ? item.koQ : item.enQ}</summary><p>{locale === "ko" ? item.koA : item.enA}</p></details>)}</div><div className="guide-note"><p>{say(locale,"요금, 입·퇴실, 추가 서비스와 환불 조건은 예약 날짜에 따라 달라질 수 있습니다. 최종 안내는 예약 상품과 호스트 메시지를 기준으로 확인해 주세요.","Rates, check-in times, optional services and cancellation terms can change. Use the current listing and host messages as your final source before booking.")}</p><a className="button button-dark" href={site.airbnb} {...external}>{say(locale,"Airbnb 본채 상품 확인","Check the Main House Listing")} ↗</a></div></div></section><Related locale={locale} items={["stay","location","reservation"]} /><BookStrip locale={locale} /></>;
}

function ExplorePage({ locale }: { locale: Locale }) { return <><PageIntro locale={locale} eyebrow="EXPLORE HONGCHEON" title={labels.explore[locale]} description={say(locale,"강산재가 있는 홍천군 서면을 천천히 둘러보세요.","Explore Seo-myeon, the Hongcheon district around Kangsanjae.")} image="mountain-view" /><section className="section"><div className="wrap"><HeaderBlock eyebrow="NEARBY LANDSCAPES" title={say(locale,"서면의 자연과 여행","Nature Around Seo-myeon")} /><p className="lead-narrow">{say(locale,"강산재의 마당과 숲길에서 하루를 보내거나, 홍천군 서면의 자연 명소를 찾아보세요. 방문 전 운영 시간과 접근 방법을 해당 장소에서 확인하는 것이 좋습니다.","Spend the day in Kangsanjae's garden and forest, or explore natural places in Seo-myeon. Check access and opening information with each destination before you go.")}</p><div className="explore-grid"><article><Picture file="misty-mountain" alt={say(locale,"강산재에서 보이는 산", "Mountain landscape at Kangsanjae")} /><div><h3>{say(locale,"강산재 주변의 산과 숲","Mountains and Forest at Kangsanjae")}</h3><p>{say(locale,"숙소에서 보이는 산 풍경과 숲길은 여행의 가장 가까운 출발점입니다.","The mountains and trees around the property are the closest place to begin exploring.")}</p><ArrowLink locale={locale} page="experiences" /></div></article><article><Picture file="palbongsan-river" alt={say(locale,"팔봉산과 홍천강 전경", "Palbongsan and the Hongcheon River")} /><div><h3>{say(locale,"팔봉산과 홍천강","Palbongsan and Hongcheon River")}</h3><p>{say(locale,"팔봉산은 홍천군 서면에 자리한 산으로, 홍천강과 함께 볼 수 있는 자연 풍경입니다. 산행·방문 조건은 홍천군 관광 안내에서 확인해 주세요.","Palbongsan is in Seo-myeon, Hongcheon, with views over the Hongcheon River. Check the county travel guide for current visiting conditions.")}</p><a className="text-link" href="https://www.hongcheon.go.kr/tour/selectTourCntntsWebView.do?key=1865&pageIndex=269&pageUnit=1000&searchCnd=all&searchShowAt=Y&tourNo=2014" {...external}>{say(locale,"홍천군 관광 안내","Hongcheon County Guide")} ↗</a></div></article></div></div></section><Related locale={locale} items={["location","gallery","reservation"]} /><BookStrip locale={locale} /></>;
}

function LocationPage({ locale }: { locale: Locale }) { const query = encodeURIComponent(site.address); return <><PageIntro locale={locale} eyebrow="GETTING HERE" title={labels.location[locale]} description={say(locale,"강산재로 향하는 길을 확인하세요.","Find your way to Kangsanjae in Hongcheon.")} image="garden-gate" /><section className="section"><div className="wrap location-grid"><div><HeaderBlock eyebrow="ADDRESS" title={say(locale,"강산재 오시는 길","How to Find Us")} /><p className="address-large">{site.address}</p><p>{site.addressEn}</p><p>{say(locale,"내비게이션에는 한글 주소를 복사해 입력해 주세요. 출발 전 지도에 표시된 목적지가 강산재인지 확인하시기 바랍니다.","Copy the Korean address into your map or navigation app. Before leaving, check that the destination pin identifies Kangsanjae.")}</p><div className="location-actions"><CopyAddress locale={locale} /><a className="button button-dark" href={`https://map.naver.com/p/search/${query}`} {...external}>{say(locale,"네이버 지도 열기","Open Naver Map")} ↗</a><a className="button button-outline" href={`https://www.google.com/maps/search/?api=1&query=${query}`} {...external}>Google Maps ↗</a></div></div><Picture file="main-exterior" alt={say(locale,"강산재 한옥 전경","Kangsanjae exterior")} /></div></section><section className="section soft-section"><div className="wrap"><HeaderBlock eyebrow="BEFORE DEPARTURE" title={say(locale,"방문 전 확인", "Before You Travel")} /><div className="info-cards"><article><h3>{say(locale,"주차","Parking")}</h3><p>{say(locale,"Airbnb 본채 상품에는 부지 내 무료 주차가 표시되어 있습니다. 주차 위치와 차량 대수는 호스트에게 확인해 주세요.","The Main House listing shows free on-site parking. Confirm its exact location and vehicle capacity with the host.")}</p></article><article><h3>{say(locale,"도착 안내","Arrival details")}</h3><p>{say(locale,"정확한 출입 방법과 도착 시간은 예약 확정 후 호스트 안내를 확인해 주세요.","Check the host's instructions after booking for exact entry and arrival details.")}</p></article></div></div></section><Related locale={locale} items={["guide","explore","reservation"]} /><BookStrip locale={locale} /></>;
}

function ReservationPage({ locale }: { locale: Locale }) { return <><PageIntro locale={locale} eyebrow="BOOK YOUR STAY" title={labels.reservation[locale]} description={say(locale,"확인된 예약 채널에서 강산재 본채의 날짜와 조건을 확인하세요.","Check dates and current terms for the Main House on the verified booking platform.")} image="evening-hanok" /><section className="section"><div className="wrap reservation-grid"><div><HeaderBlock eyebrow="MAIN HOUSE BOOKING" title={say(locale,"강산재 본채 예약", "Book the Main House")} /><p>{say(locale,"현재 확인된 본채 예약 상품은 Airbnb에서 열립니다. 날짜와 인원, 최종 요금, 숙소 규정은 이동한 예약 화면에서 확인하고 결제할 수 있습니다.","The verified Main House listing opens on Airbnb. Select your dates and guests there, review the final price and house rules, and complete your booking on the platform.")}</p><a className="button button-dark button-large" href={site.airbnb} {...external}>{say(locale,"Airbnb에서 본채 예약하기", "Book the Main House on Airbnb")} ↗</a><p className="small-note">{say(locale,"예약·결제와 호스트 메시지는 Airbnb에서 진행됩니다.","Booking, payment and messages to the host are handled by Airbnb.")}</p></div><Picture file="living-room" alt={say(locale,"본채 실내 공간","Main House interior")} /></div></section><section className="section soft-section"><div className="wrap"><HeaderBlock eyebrow="BEFORE BOOKING" title={say(locale,"예약 전 확인하세요", "Before You Book")} /><div className="info-cards"><article><h3>{say(locale,"날짜와 인원", "Dates and guests")}</h3><p>{say(locale,"희망 날짜의 예약 가능 여부와 인원 조건을 상품 화면에서 확인해 주세요.","Check availability and guest rules for your preferred dates on the listing.")}</p></article><article><h3>{say(locale,"추가 이용", "Optional activities")}</h3><p>{say(locale,"불멍·바비큐 등은 제공 가능 여부와 조건을 예약 전 호스트에게 문의해 주세요.","Ask the host about the availability and terms of firepit or barbecue use before booking.")}</p></article><article><h3>{say(locale,"문의", "Questions")}</h3><p>{say(locale,"예약 관련 문의는 Airbnb 상품의 호스트 메시지 기능 또는 공식 인스타그램을 이용해 주세요.","For booking questions, message the host through Airbnb or use the official Instagram account.")}</p><a className="text-link" href={site.instagram} {...external}>Instagram ↗</a></article></div></div></section><Related locale={locale} items={["mainHouse","guide","location"]} /></>;
}

const pages: Record<PageKey, (props: { locale: Locale }) => React.ReactNode> = { home: HomePage, about: AboutPage, filming: FilmingPage, stay: StayPage, mainHouse: MainHousePage, experiences: ExperiencesPage, gallery: GalleryPage, guide: GuidePage, explore: ExplorePage, location: LocationPage, reservation: ReservationPage };
export function PageView({ locale, page }: { locale: Locale; page: PageKey }) {
  const Content = pages[page];
  const lodgingData = page === "home" ? { "@context": "https://schema.org", "@type": "LodgingBusiness", name: site.name, alternateName: site.englishName, description: descriptions.home[locale], address: { "@type": "PostalAddress", streetAddress: "고루개길 110", addressLocality: "홍천군", addressRegion: "강원특별자치도", addressCountry: "KR" }, sameAs: [site.instagram, site.airbnb] } : null;
  return <Shell locale={locale} current={page}>{lodgingData && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(lodgingData) }} />}<Content locale={locale} /></Shell>;
}
